# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

stages:
  # - install-dep
  # - build
  - test
  - spell-check


test:
  needs: []
  stage: test
  image: registry.internal.psych.dev/internal-che/che-dockerfile/che-node-angular:node-12.18.3.angular-10.0.7
  script:
    - yarn install
    - yarn build jspsych
    - yarn build jspsych-angular
    - yarn test jspsych
    - yarn test jspsych-angular
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
    policy: pull-push
  only:
    - master
    - merge_requests

spell-check:
  image: python:3.8
  script:
    - pip3 install codespell
    - codespell -c -f src/* projects/*
  only:
    - master
    - merge_requests




# install-dep:
#   stage: install-dep
#   script:
#     - yarn install
#   cache:
#     key: "$CI_COMMIT_REF_SLUG"
#     paths:
#       - node_modules/
#     policy: pull-push

# build:
#   stage: build
#   script:
#     - yarn build jspsych
#     - yarn build jspsych-angular
#   artifacts:
#     paths:
#       - dist/
#   cache:
#     key: "$CI_COMMIT_REF_SLUG"
#     paths:
#       - node_modules/
#     policy: pull

# test-jspsych-library:
#   stage: test
#   needs: 
#     job: build
#     artifacts: true
#   script:
#     - yarn test jspsych
#   cache:
#     key: "$CI_COMMIT_REF_SLUG"
#     paths:
#       - node_modules/
#     policy: pull

# test-jspsych-app:
#   stage: test
#   needs: 
#     job: build
#     artifacts: true
#   cache:
#     key: "$CI_COMMIT_REF_SLUG"
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - yarn test jspsych-angular
