# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
stages:
  - install-dep
  - build
  - test

image: registry.internal.psych.dev/internal-che/che-dockerfile/che-node-angular:node-12.18.3.angular-10.0.7

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

install-dep:
  stage: install-dep
  script:
    - yarn install

build:
  stage: build
  script:
    - yarn build jspsych
    - yarn build jspsych-angular
  artifacts:
    paths:
      - dist/

test-jspsych-library:
  stage: test
  needs: 
    job: build_job
    artifacts: true
  script:
    - yarn test jspsych

test-jspsych-app:
  stage: test
  needs: 
    job: build_job
    artifacts: true
  script:
    - yarn test jspsych-angular
